#!/usr/bin/env python3
"""
snapshot_catalog.py — writes the catalog snapshot the navigator ships with.

Output: skills/besci-navigator/references/catalog.md

The navigator is installed as a zip that never updates itself, so it carries
a snapshot of the whole catalog. CI re-runs this on every merge to main and
commits the result when it changed.

Deterministic: the only non-content line is "Snapshot date". If the existing
file differs from the new content only by that line, the file is left alone
so repeated runs produce no diff. Override the date with SNAPSHOT_DATE=YYYY-MM-DD.

Usage:
  uv run scripts/snapshot_catalog.py
"""
from __future__ import annotations

import datetime as dt
import os
import re
import sys
from typing import Dict, List

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import besci_validate as v  # noqa: E402

ROOT = v.find_repo_root(os.path.dirname(os.path.abspath(__file__))) or os.getcwd()
SKILLS_DIR = os.path.join(ROOT, "skills")
OUT = os.path.join(SKILLS_DIR, "besci-navigator", "references", "catalog.md")
DATE_LINE_RE = re.compile(r"^Snapshot date: \d{4}-\d{2}-\d{2}$", re.MULTILINE)


def cell(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def labels(items) -> Dict[str, str]:
    out = {}
    for it in items or []:
        if isinstance(it, dict):
            out[str(it.get("id"))] = str(it.get("label") or it.get("id"))
    return out


def build(date: str) -> str:
    taxonomy = v.load_taxonomy(os.path.join(ROOT, "taxonomy.yaml"))
    entries: List[dict] = []
    for folder in v.discover_skills(SKILLS_DIR):
        sk = v.validate_skill(v.parse_skill(folder), taxonomy)
        e = v.catalog_entry(sk)
        e["name"] = e["name"] or os.path.basename(folder)
        entries.append(e)
    entries.sort(key=lambda e: e["name"])
    stage_labels = labels(taxonomy.get("stages"))
    io_labels = labels(taxonomy.get("io_types"))

    lines: List[str] = []
    lines.append("# Catalog snapshot")
    lines.append("")
    lines.append(f"Snapshot date: {date}")
    lines.append("")
    lines.append("This file is generated by `scripts/snapshot_catalog.py` from the skills in the repository. Do not edit by hand. "
                 "It lists every skill in the Behavioral Science Skills Library, what each one does, when it fires, when it should not, "
                 "when it escalates to a specialist, and how skills chain. The live catalog is at https://behav-sci-skills.vercel.app/ "
                 "and as JSON at https://behav-sci-skills.vercel.app/data/catalog.json.")
    lines.append("")
    lines.append(f"Skills in this snapshot: {len(entries)}")
    lines.append("")

    # Table
    lines.append("## All skills")
    lines.append("")
    lines.append("| Name | Title | Stage | Type | Status | Version | Consumes | Produces | What it does |")
    lines.append("|---|---|---|---|---|---|---|---|---|")
    for e in entries:
        lines.append("| " + " | ".join(cell(x) for x in [
            e["name"], e["title"], e["stage"], e["type"], e["status"], e["version"],
            ", ".join(e["consumes"]) or "—", ", ".join(e["produces"]) or "—", e["what_it_does"],
        ]) + " |")
    lines.append("")

    # Per-skill blocks
    lines.append("## Skill details")
    lines.append("")
    for e in entries:
        lines.append(f"### {e['name']}")
        lines.append("")
        lines.append(f"**Title:** {e['title']}  ")
        lines.append(f"**Stage:** {stage_labels.get(e['stage'], e['stage'])} · **Type:** {e['type']} · **Status:** {e['status']} · **Version:** {e['version']} · **Org:** {e['org']}  ")
        if e["tags"]:
            lines.append(f"**Tags:** {', '.join(e['tags'])}  ")
        if e["consumes"]:
            lines.append(f"**Consumes:** {', '.join(e['consumes'])}  ")
        if e["produces"]:
            lines.append(f"**Produces:** {', '.join(e['produces'])}  ")
        lines.append("")
        lines.append(f"**What it does:** {e['what_it_does']}")
        lines.append("")
        lines.append(f"**Description (trigger rule):** {e['description']}")
        lines.append("")
        if e["use_when"]:
            lines.append("**Use it when:**")
            for b in e["use_when"]:
                lines.append(f"- {b}")
            lines.append("")
        if e["do_not_use_when"]:
            lines.append("**Do not use it when:**")
            for b in e["do_not_use_when"]:
                lines.append(f"- {b}")
            lines.append("")
        spec = e["sections"].get("When to bring in a specialist", "").strip()
        if spec:
            lines.append("**When to bring in a specialist:**")
            lines.append("")
            lines.append(spec)
            lines.append("")

    # Chains
    lines.append("## Chains")
    lines.append("")
    lines.append("Edges where one skill produces what another consumes. A user-suppliable input can also come straight from the person.")
    lines.append("")
    producers: Dict[str, List[str]] = {}
    consumers: Dict[str, List[str]] = {}
    for e in entries:
        for t in e["produces"]:
            producers.setdefault(t, []).append(e["name"])
        for t in e["consumes"]:
            consumers.setdefault(t, []).append(e["name"])
    edges = []
    for t in sorted(set(producers) | set(consumers)):
        for p in producers.get(t, []):
            for c in consumers.get(t, []):
                if p != c:
                    edges.append(f"- {p} → {c} (via `{t}`: {io_labels.get(t, t)})")
    if edges:
        lines.extend(edges)
    else:
        lines.append("- No chains yet.")
    lines.append("")
    dangling = sorted(t for t in consumers if t not in producers)
    if dangling:
        lines.append("Inputs no skill produces yet (the user supplies them, or a skill is missing):")
        for t in dangling:
            lines.append(f"- `{t}` ({io_labels.get(t, t)}): consumed by {', '.join(consumers[t])}")
        lines.append("")

    # Stages
    lines.append("## Stages")
    lines.append("")
    for st in taxonomy.get("stages", []):
        if not isinstance(st, dict):
            continue
        cw = st.get("crosswalk") or {}
        cw_txt = ""
        if cw:
            cw_txt = " (" + "; ".join(f"{k}: {val}" for k, val in cw.items()) + ")"
        lines.append(f"- **{st.get('id')}** — {st.get('label')}: {st.get('description', '')}{cw_txt}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    date = os.environ.get("SNAPSHOT_DATE") or dt.date.today().isoformat()
    content = build(date)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    if os.path.exists(OUT):
        with open(OUT, "r", encoding="utf-8") as fh:
            old = fh.read()
        if DATE_LINE_RE.sub("Snapshot date: X", old) == DATE_LINE_RE.sub("Snapshot date: X", content):
            print(f"Unchanged: {os.path.relpath(OUT, ROOT)}")
            return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"Wrote {os.path.relpath(OUT, ROOT)} ({date})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
